name: Update Npm By Yarn pub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 16
      
      - name: 安装依赖
        run: npm install

      - name: 安装 TypeScript
        run: yarn add -D typescript

      - name: Build
        run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      - name: Install Dependencies
        run: npm ci

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 16

      - name: Publish to npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
